### PR TITLE
added avatar image to profile

### PR DESCRIPTION
**Pull request by sahilg861907**
Added an avatar to profile using cartoon-avatar dependency.

### CODE REVIEW

**Comment by chehak123** [comment]
Please add screenshots and also resolve conflicts

**Comment by sahilg861907** [comment]
https://user-images.githubusercontent.com/76491963/156932866-d9c02802-91bc-471d-9d77-57939c7824e1.mp4

**Comment by sahilg861907** [comment]
WhatsApp Image 2022-03-05 at 4 39 45 PM

**Comment by sahilg861907** [comment]
@chehak123 Please look into the changes. I have attached screen record and screenshot.

**Comment by chehak123** [comment]
Good job!!
Also add the Avatar generated on profile page

**Comment by sahilg861907** [comment]
ok. I added the same. please look into attached screenshot, and suggest me if any improvement is needed.
image

**Comment by sahilg861907** [comment]
@chehak123 I hope you have gone through the changes. If this pull request requires some improvement/changes, suggest the same.

**Comment by Swatilekha-Roy** [comment]
Hello, @sahilg861907, really good job on the issue so far! However, here is a gentle reminder for you to please resolve the merge conflicts on your end so that we can merge your pr. Thanks.

**Comment by sahilg861907** [comment]
Done!

**Pull request merged**
