### PR TITLE
Confirm password field added

### LINKED ISSUE #32: Confirm password field
There should be a confirm password field while signing up the page.
If both the password matches then only use should be registered successfully else it should throw an error.

I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
Closes #32 

I have added confirm password field and also toggle password visibility to it.
I also handled the backend(if password and confirm password doesn't match, user doesn't get registered.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @Swatilekha-Roy 
Please review this PR.

**Comment by Swatilekha-Roy** [comment]
@Siddhesh777 good job, but please attach a screen recording of your issue being fixed with your pr and commit. I'll review it after that. Thanks.

**Comment by Siddhesh777** [comment]
hey @Swatilekha-Roy here it is


https://user-images.githubusercontent.com/77476772/162148975-9dc83805-1655-44f3-8231-163e302454f6.mp4

**Comment by Siddhesh777** [comment]
hey @Swatilekha-Roy 
Please review the PR.

**Comment by Siddhesh777** [comment]
hey @chehak123 
Please add labels

**Comment by Siddhesh777** [comment]
hey @chehak123 @Swatilekha-Roy 
Can you please add labels
Also it will be great help if you add level3 or level2 label as there was both frontend and backend part was covered.
Also add the label of Gssoc.

**Comment by Siddhesh777** [comment]
@Swatilekha-Roy @chehak123 
Please add the labels

**Comment by Siddhesh777** [comment]
@Swatilekha-Roy @chehak123 
Please add the labels

**Pull request merged**
