### PR TITLE
Added CODE_OF_CONDUCT.md and CONTRIBUTION.md file.

### LINKED ISSUE #34: Add CODE_OF_CONDUCT.md and Contribute.md file
I saw that in this project CODE_OF_CONDUCT.md and Contribute.md file are missing.
I'd like to add these files in the project.
I'd be grateful if you could assign this task to me under GSSoC'22.
@Swatilekha-Roy @chehak123 

PS: the level labels which you are assigning to the issues will not have spaces between them.
It's written as "Level 2" but it should be written as "Level2".

### PR DESCRIPTION
**Pull request by Sukriti-m**
I have added CODE_OF_CONDUCT.md and CONTRIBUTION.md file.

Fixes #34 

### Video Of CODE_OF_CONDUCT.md file

https://user-images.githubusercontent.com/93239528/161935111-108bde44-89b6-46b1-a841-0ba759b6476a.mp4

### Video Of CONTRIBUTION.md file

https://user-images.githubusercontent.com/93239528/162203896-39a5a50e-566f-4b22-ad73-83b73ceb9d55.mp4

@Swatilekha-Roy Please review it.

### CODE REVIEW

**Comment by Swatilekha-Roy** [comment]
Great job so far, @Sukriti-m! And thank you very much for uploading the recordings too for easy review.
Just one small piece of feedback so far: For the CONTRIBUTION.md file, would you mind removing the red hand-drawn marks from the screenshots instead of using highlighted hollow boxes around the part of the screenshot you are trying to highlight? That should look neater.

Let me know once you are done, I'll merge your pr.

Fantastic job so far! Keep going.

**Comment by Sukriti-m** [comment]
Hi @Swatilekha-Roy 
Thank you so much for the appreciation.😃 
I have made the required changes and I have also updated the PR with the new video of CONTRIBUTION.md file.
Kindly review it.

**Comment by Sukriti-m** [comment]
Hi @chehak123 
Thanks for merging the PR.
 But I request you to please add the GSSoC22 and Level1 labels to this PR as assigned in the issue #34 .
I'd be grateful for it.

**Comment by Sukriti-m** [comment]
Hi @Swatilekha-Roy @chehak123
Thanks for merging the PR.
But I request you to please add the GSSoC22 and Level1 labels to this PR as assigned in the issue https://github.com/Fem-STEM/FemSTEM-Web-App/issues/34 .
I'd be grateful for it.

**Comment by Sukriti-m** [comment]
Hi @Swatilekha-Roy @chehak123
Thanks for merging the PR.
But I request you to please add the GSSoC22 and Level1 labels to this PR as assigned in the issue https://github.com/Fem-STEM/FemSTEM-Web-App/issues/34 .
I'd be grateful for it.

**Pull request merged**
